### ISSUE TITLE
OSX error with open 'SP Delegation' page

### ISSUE THREAD

**Issue by soosgit** [aaroncox/vessel#7]
i'm uss vessel on macOS Sierra 10.12.5.
and update 0.0.5 version vessel to 0.0.6 with replace application file.

and, open account tab, click SP Deleation menu. but page does not change.
i see below error in developer tool.

```
Uncaught TypeError: Cannot read property '$username' of undefined
    at Le.map (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:1:21596)
    at Array.map (native)
    at je.render (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:1:21504)
    at me._renderValidatedComponentWithoutOwnerOrContext (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:64123)
    at me._renderValidatedComponent (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:64260)
    at me.performInitialMount (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:59801)
    at me.mountComponent (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:58769)
    at Object.mountComponent (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:116075)
    at Object.updateChildren (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:54754)
    at pe._reconcilerUpdateChildren (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:111429)
    at pe._updateChildren (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:112272)
    at pe.updateChildren (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:112160)
    at pe._updateDOMChildren (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:77961)
    at pe.updateComponent (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:76064)
    at pe.receiveComponent (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:75576)
    at Object.receiveComponent (file:///Applications/Vessel.app/Contents/Resources/app.asar/dist/bundle.js:16:116513)
Le.map @ bundle.js:formatted:1054
render @ bundle.js:formatted:1052
_renderValidatedComponentWithoutOwnerOrContext @ bundle.js:formatted:72367
_renderValidatedComponent @ bundle.js:formatted:72376
performInitialMount @ bundle.js:formatted:72221
mountComponent @ bundle.js:formatted:72189
mountComponent @ bundle.js:formatted:74520
updateChildren @ bundle.js:formatted:72045
_reconcilerUpdateChildren @ bundle.js:formatted:74319
_updateChildren @ bundle.js:formatted:74360
updateChildren @ bundle.js:formatted:74354
_updateDOMChildren @ bundle.js:formatted:72898
updateComponent @ bundle.js:formatted:72837
receiveComponent @ bundle.js:formatted:72813
receiveComponent @ bundle.js:formatted:74539
_updateRenderedComponent @ bundle.js:formatted:72350
_performComponentUpdate @ bundle.js:formatted:72341
updateComponent @ bundle.js:formatted:72309
receiveComponent @ bundle.js:formatted:72288
receiveComponent @ bundle.js:formatted:74539
_updateRenderedComponent @ bundle.js:formatted:72350
_performComponentUpdate @ bundle.js:formatted:72341
updateComponent @ bundle.js:formatted:72309
performUpdateIfNecessary @ bundle.js:formatted:72291
performUpdateIfNecessary @ bundle.js:formatted:74546
oe @ bundle.js:formatted:74766
perform @ bundle.js:formatted:75713
perform @ bundle.js:formatted:75713
perform @ bundle.js:formatted:74819
xe @ bundle.js:formatted:74827
closeAll @ bundle.js:formatted:75749
perform @ bundle.js:formatted:75722
batchedUpdates @ bundle.js:formatted:73681
batchedUpdates @ bundle.js:formatted:74843
dispatchEvent @ bundle.js:formatted:73863
bundle.js:formatted:110008 action ACCOUNT_DATA_UPDATE_PENDING @ 14:50:38.683
bundle.js:formatted:110008 action ACCOUNT_DATA_UPDATE @ 14:50:39.036
bundle.js:formatted:74526Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (bundle.js:formatted:74526)
    at me.getHostNode (bundle.js:formatted:72230)
    at Object.getHostNode (bundle.js:formatted:74526)
    at Object.updateChildren (bundle.js:formatted:72041)
    at pe._reconcilerUpdateChildren (bundle.js:formatted:74319)
    at pe._updateChildren (bundle.js:formatted:74360)
    at pe.updateChildren (bundle.js:formatted:74354)
    at pe._updateDOMChildren (bundle.js:formatted:72898)
    at pe.updateComponent (bundle.js:formatted:72837)
    at pe.receiveComponent (bundle.js:formatted:72813)
    at Object.receiveComponent (bundle.js:formatted:74539)
    at me._updateRenderedComponent (bundle.js:formatted:72350)
    at me._performComponentUpdate (bundle.js:formatted:72341)
    at me.updateComponent (bundle.js:formatted:72309)
    at me.receiveComponent (bundle.js:formatted:72288)
    at Object.receiveComponent (bundle.js:formatted:74539)
```

**Comment by aaroncox** [comment]
I think that was [fixed in 0.0.6a](https://github.com/aaroncox/vessel/releases/tag/v0.0.6-a), are you using 0.0.6 or 0.0.6a?

**Comment by noisy** [comment]
on Ubuntu 14.04, I cannot open SP Delegation tab :cry: 

![vessel_sp_delegation](https://cloud.githubusercontent.com/assets/201263/26438346/bd6e3d36-4122-11e7-89a0-c90a00f30254.gif)

**Comment by aaroncox** [comment]
Can you guys try 0.0.6b and let me know if it's working? 

https://github.com/aaroncox/vessel/releases/tag/v0.0.6-b

I think there were some issues with ES5 and the NumericLabel component I'm using. The whole thing needs to be rewritten, I just haven't gotten around to it yet.

**Comment by noisy** [comment]
on v0.0.6-b I still have the same problem

**Comment by aaroncox** [comment]
Alright, well I think it fixed the blank page problem you were encountering before at the very least 👍 

I haven't been able to reproduce the issue with the Steem Delegation page not working yet.

**Comment by soosgit** [comment]
yes.. i still have the same problem too on v0.0.6b.
you cannot reproduce this issue? 

I'll trying fix it on weekend a two days later. (GMT +09:00)
it was might simple issue.
You can take care of other things.

**Comment by noisy** [comment]
I can confirm that I have the same issue on Windows 10.

**Comment by aaroncox** [comment]
DevTools should be enabled now in 0.0.6-c. 

Could one of you folks update to the newest build and let me know what errors appear in the console when you try to load the SP Delegation tab?

**Comment by jemekite** [comment]
Bug still exist on v0.0.6-c, Ubuntu 16.04.2
Logs from devtools:
```
Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at me.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:64)
    at Object.updateChildren (ReactChildReconciler.js:113)
    at pe._reconcilerUpdateChildren (ReactMultiChild.js:213)
    at pe._updateChildren (ReactMultiChild.js:312)
    at pe.updateChildren (ReactMultiChild.js:299)
    at pe._updateDOMChildren (ReactDOMComponent.js:936)
    at pe.updateComponent (ReactDOMComponent.js:754)
    at pe.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at me._updateRenderedComponent (ReactCompositeComponent.js:754)
    at me._performComponentUpdate (ReactCompositeComponent.js:724)
    at me.updateComponent (ReactCompositeComponent.js:645)
    at me.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:64
updateChildren @ ReactChildReconciler.js:113
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:149
oe @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
xe @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
ae @ ReactUpdates.js:208
J @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:219
J.setState @ ReactComponent.js:63
Ye.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:28
ae.notifyNestedSubs @ Subscription.js:63
Ye.onStateChange @ connectAdvanced.js:204
me @ createStore.js:176
(anonymous) @ middleware.js:13
(anonymous) @ redux-logger.js:1
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:35
Te.default.api.getAccounts @ account.js:169
tryCatcher @ util.js:16
$ @ nodeify.js:23
$._settlePromise @ promise.js:571
$._settlePromise0 @ promise.js:614
$._settlePromises @ promise.js:693
J._drainQueue @ async.js:134
J._drainQueues @ async.js:143
J.drainQueues @ async.js:18
_tickCallback @ internal/process/next_tick.js:103
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at me.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:64)
    at Object.updateChildren (ReactChildReconciler.js:113)
    at pe._reconcilerUpdateChildren (ReactMultiChild.js:213)
    at pe._updateChildren (ReactMultiChild.js:312)
    at pe.updateChildren (ReactMultiChild.js:299)
    at pe._updateDOMChildren (ReactDOMComponent.js:936)
    at pe.updateComponent (ReactDOMComponent.js:754)
    at pe.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at me._updateRenderedComponent (ReactCompositeComponent.js:754)
    at me._performComponentUpdate (ReactCompositeComponent.js:724)
    at me.updateComponent (ReactCompositeComponent.js:645)
    at me.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:64
updateChildren @ ReactChildReconciler.js:113
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:149
oe @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
xe @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
ae @ ReactUpdates.js:208
J @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:219
J.setState @ ReactComponent.js:63
Ye.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:28
ae.notifyNestedSubs @ Subscription.js:63
Ye.onStateChange @ connectAdvanced.js:204
me @ createStore.js:176
(anonymous) @ middleware.js:13
(anonymous) @ redux-logger.js:1
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:35
oe.default.api.getDynamicGlobalProperties @ steem.js:17
tryCatcher @ util.js:16
$ @ nodeify.js:23
$._settlePromise @ promise.js:571
$._settlePromise0 @ promise.js:614
$._settlePromises @ promise.js:693
J._drainQueue @ async.js:134
J._drainQueues @ async.js:143
J.drainQueues @ async.js:18
_tickCallback @ internal/process/next_tick.js:103
redux-logger.js:1  action ACCOUNT_DATA_UPDATE_PENDING @ 20:54:01.801
redux-logger.js:1  action ACCOUNT_DATA_UPDATE @ 20:54:02.774
redux-logger.js:1  action STEEM_GLOBALPROPS_UPDATE_RESOLVED @ 20:54:02.790
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at me.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:64)
    at Object.updateChildren (ReactChildReconciler.js:113)
    at pe._reconcilerUpdateChildren (ReactMultiChild.js:213)
    at pe._updateChildren (ReactMultiChild.js:312)
    at pe.updateChildren (ReactMultiChild.js:299)
    at pe._updateDOMChildren (ReactDOMComponent.js:936)
    at pe.updateComponent (ReactDOMComponent.js:754)
    at pe.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at me._updateRenderedComponent (ReactCompositeComponent.js:754)
    at me._performComponentUpdate (ReactCompositeComponent.js:724)
    at me.updateComponent (ReactCompositeComponent.js:645)
    at me.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:64
updateChildren @ ReactChildReconciler.js:113
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:149
oe @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
xe @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
ae @ ReactUpdates.js:208
J @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:219
J.setState @ ReactComponent.js:63
Ye.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:28
ae.notifyNestedSubs @ Subscription.js:63
Ye.onStateChange @ connectAdvanced.js:204
me @ createStore.js:176
(anonymous) @ middleware.js:13
(anonymous) @ redux-logger.js:1
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:35
Te.default.api.getAccounts @ account.js:169
tryCatcher @ util.js:16
$ @ nodeify.js:23
$._settlePromise @ promise.js:571
$._settlePromise0 @ promise.js:614
$._settlePromises @ promise.js:693
J._drainQueue @ async.js:134
J._drainQueues @ async.js:143
J.drainQueues @ async.js:18
_tickCallback @ internal/process/next_tick.js:103
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at me.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:64)
    at Object.updateChildren (ReactChildReconciler.js:113)
    at pe._reconcilerUpdateChildren (ReactMultiChild.js:213)
    at pe._updateChildren (ReactMultiChild.js:312)
    at pe.updateChildren (ReactMultiChild.js:299)
    at pe._updateDOMChildren (ReactDOMComponent.js:936)
    at pe.updateComponent (ReactDOMComponent.js:754)
    at pe.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at me._updateRenderedComponent (ReactCompositeComponent.js:754)
    at me._performComponentUpdate (ReactCompositeComponent.js:724)
    at me.updateComponent (ReactCompositeComponent.js:645)
    at me.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:64
updateChildren @ ReactChildReconciler.js:113
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:149
oe @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
xe @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
ae @ ReactUpdates.js:208
J @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:219
J.setState @ ReactComponent.js:63
Ye.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:28
ae.notifyNestedSubs @ Subscription.js:63
Ye.onStateChange @ connectAdvanced.js:204
me @ createStore.js:176
(anonymous) @ middleware.js:13
(anonymous) @ redux-logger.js:1
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:35
oe.default.api.getDynamicGlobalProperties @ steem.js:17
tryCatcher @ util.js:16
$ @ nodeify.js:23
$._settlePromise @ promise.js:571
$._settlePromise0 @ promise.js:614
$._settlePromises @ promise.js:693
J._drainQueue @ async.js:134
J._drainQueues @ async.js:143
J.drainQueues @ async.js:18
_tickCallback @ internal/process/next_tick.js:103
redux-logger.js:1  action ACCOUNT_DATA_UPDATE_PENDING @ 20:54:11.800
redux-logger.js:1  action ACCOUNT_DATA_UPDATE @ 20:54:12.441
redux-logger.js:1  action STEEM_GLOBALPROPS_UPDATE_RESOLVED @ 20:54:12.452
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at me.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:64)
    at Object.updateChildren (ReactChildReconciler.js:113)
    at pe._reconcilerUpdateChildren (ReactMultiChild.js:213)
    at pe._updateChildren (ReactMultiChild.js:312)
    at pe.updateChildren (ReactMultiChild.js:299)
    at pe._updateDOMChildren (ReactDOMComponent.js:936)
    at pe.updateComponent (ReactDOMComponent.js:754)
    at pe.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at me._updateRenderedComponent (ReactCompositeComponent.js:754)
    at me._performComponentUpdate (ReactCompositeComponent.js:724)
    at me.updateComponent (ReactCompositeComponent.js:645)
    at me.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
getHostNode @ ReactReconciler.js:63
getHostNode @ ReactCompositeComponent.js:384
getHostNode @ ReactReconciler.js:64
updateChildren @ ReactChildReconciler.js:113
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:149
oe @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
xe @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
ae @ ReactUpdates.js:208
J @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:219
J.setState @ ReactComponent.js:63
Ye.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:28
ae.notifyNestedSubs @ Subscription.js:63
Ye.onStateChange @ connectAdvanced.js:204
me @ createStore.js:176
(anonymous) @ middleware.js:13
(anonymous) @ redux-logger.js:1
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:35
Te.default.api.getAccounts @ account.js:169
tryCatcher @ util.js:16
$ @ nodeify.js:23
$._settlePromise @ promise.js:571
$._settlePromise0 @ promise.js:614
$._settlePromises @ promise.js:693
J._drainQueue @ async.js:134
J._drainQueues @ async.js:143
J.drainQueues @ async.js:18
_tickCallback @ internal/process/next_tick.js:103
ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:63)
    at me.getHostNode (ReactCompositeComponent.js:384)
    at Object.getHostNode (ReactReconciler.js:64)
    at Object.updateChildren (ReactChildReconciler.js:113)
    at pe._reconcilerUpdateChildren (ReactMultiChild.js:213)
    at pe._updateChildren (ReactMultiChild.js:312)
    at pe.updateChildren (ReactMultiChild.js:299)
    at pe._updateDOMChildren (ReactDOMComponent.js:936)
    at pe.updateComponent (ReactDOMComponent.js:754)
    at pe.receiveComponent (ReactDOMComponent.js:716)
    at Object.receiveComponent (ReactReconciler.js:125)
    at me._updateRenderedComponent (ReactCompositeComponent.js:754)
    at me._performComponentUpdate (ReactCompositeComponent.js:724)
    at me.updateComponent (ReactCompositeComponent.js:645)
    at me.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
```

**Comment by aaroncox** [comment]
Next build should resolve this issue. I'm going to address a couple other bugs and make the release soon.

**Comment by Webdeals85** [comment]
Hi I am having the same problem. I am clicking on Accounts then SP delegation but nothing happens like here 
https://cloud.githubusercontent.com/assets/201263/26438346/bd6e3d36-4122-11e7-89a0-c90a00f30254.gif

**Comment by 4Ykw** [comment]
@Webdeals85, download the latest version and it should be fixed.

**Comment by Webdeals85** [comment]
@4Ykw  do you mean the 0006c? I have this and the issue is still there!

**Comment by aaroncox** [comment]
0.0.0f is the newest

**Comment by Webdeals85** [comment]
thank you @aaroncox   got it thank you again
